### ISSUE TITLE
error：Error in run

### ISSUE THREAD

**Issue by G36maid** [Panda7122/MusicThumbnailGenerator#2]
```
Fetching 16 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [04:57<00:00, 18.62s/it]
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 13.94it/s]
done init_pytorch_model.fp16.safetensors:  38%|███████████████████████████████████████████████████████▌                                                                                           | 650M/1.72G [02:59<03:18, 5.39MB/s]
Traceback (most recent call last):ensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.72G/1.72G [04:56<00:00, 9.08MB/s]
****

  File "/app/lyrisOnlyModel.py", line 142, in <module>
    main()
  File "/app/lyrisOnlyModel.py", line 139, in main
    traning(lyrisfile, bert_model, tokenizer, model, diffusionModel, title, artist)
  File "/app/lyrisOnlyModel.py", line 80, in traning
    lyris_vector = BERT(**lyrisinputs).last_hidden_state[:, 0, :].to(device)
                   ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/transformers/models/bert/modeling_bert.py", line 1078, in forward
    embedding_output = self.embeddings(
                       ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/transformers/models/bert/modeling_bert.py", line 217, in forward
    embeddings += position_embeddings
RuntimeError: The size of tensor a (551) must match the size of tensor b (512) at non-singleton dimension 1
```

**Comment by Panda7122** [comment]
push, try it
