### ISSUE TITLE
error: Error on run

### ISSUE THREAD

**Issue by G36maid** [Panda7122/MusicThumbnailGenerator#3]
Fetching 16 files: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 16/16 [04:07<00:00, 15.45s/it]
Loading pipeline components...: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 7/7 [00:00<00:00, 12.95it/s]
done init_pytorch_model.fp16.safetensors:  35%|████████████████████████████████████████████████████                                                                                               | 608M/1.72G [02:23<03:32, 5.24MB/s]
Traceback (most recent call last):ensors: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.72G/1.72G [04:05<00:00, 11.4MB/s]
  File "/app/lyrisOnlyModel.py", line 142, in <module>
    main()
  File "/app/lyrisOnlyModel.py", line 139, in main
    traning(lyrisfile, bert_model, tokenizer, model, diffusionModel, title, artist)
  File "/app/lyrisOnlyModel.py", line 82, in traning
    diffusion_input = Adaptermodel.get_diffusion_input(lyris_vector)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lyrisOnlyModel.py", line 54, in get_diffusion_input
    diffusion_input = self.forward(lyris_vector)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lyrisOnlyModel.py", line 48, in forward
    embedded_seq = self.embedding(lyris_vector)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/torch/nn/modules/sparse.py", line 164, in forward
    return F.embedding(
           ^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/torch/nn/functional.py", line 2267, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Expected tensor for argument #1 'indices' to have one of the following scalar types: Long, Int; but got torch.cuda.FloatTensor instead (while checking arguments for embedding)

**Comment by Panda7122** [comment]
pushed
I think it's embedding issue, I replace it by linear layer
